In [1]:
import numpy as np
import json
from utilities import *
import torch
# print(torch.version.cuda)

In [8]:
SNRVec = np.arange(0, 21, 2, dtype=int)
FFTsize = 4096
tauVec = np.array([64, 256, 333, 667, 1333])
freqBinList = [[51, 57], [13, 14, 15], [10, 12]]
symLenList = [[80, 72], [320, 288, 272], [640, 548]]
CPLenList = np.array([np.array(['Extended', 'Normal']),\
    np.array(['Extended', 'Medium', 'Normal']),\
    np.array(['Extended', 'Normal']),\
    np.array(['Normal']), np.array(['Normal'])], dtype=object)
protocolList = np.array(['wlanHT', 'wlanHE', 'NRDLa', 'NRDLb', 'NRDLc'])

CPLenList.shape

(5,)

In [14]:
fileCount = np.zeros((len(protocolList),), dtype=object)
for i in range(len(protocolList)):
    fileCount[i] = np.zeros((len(SNRVec), CPLenList[i].shape[0]))
    # fileCount = np.zeros((len(SNRVec), len(protocolList)))
    corrNSubCCount = np.zeros((len(SNRVec), len(protocolList)))
    corrSymLenCount = np.zeros((len(SNRVec), len(protocolList)))

print(fileCount)

[array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]) array([[0., 0., 0.],
                          [0., 0., 0.],
                          [0., 0., 0.],
                          [0., 0., 0.],
                          [0., 0., 0.],
                          [0., 0., 0.],
                          [0., 0., 0.],
                          [0., 0., 0.],
                          [0., 0., 0.],
                          [0., 0., 0.],
                          [0., 0., 0.]]) array([[0., 0.],
                                                [0., 0.],
                                                [0., 0.],
                                                [0., 0.],
                                                [0., 0.],
                                                [0., 0.],
                                                [0., 0.],
              

In [3]:
f = open('/project/iarpa/dataset/cyclo_modul_OFDM/simulation/test/wlanHE_Extended_16_0_100_20_0.4_1.metadata')
loadMetadata = json.load(f)

MCSlist = getMCS_HEMU(loadMetadata)
print(MCSlist)

[3 3 3 3 3 3 3 3 3]


In [23]:
load_out = np.fromfile('/project/iarpa/dataset/cyclo_modul_OFDM/walk_test/test/wlanHT_Extended_2_0_100_20_0.4_1.32cf',\
    dtype=np.float32)
data = load_out[np.arange(0, load_out.shape[0], 2)] +\
                    1j * load_out[np.arange(1, load_out.shape[0], 2)]

inputIQ = data[1200:]
print(inputIQ.shape[0])

6800


In [24]:
CPLen = 8

CAF_DC = getCAF_DC(inputIQ, tauVec, CPLen)
nSubC_Est = tauVec[np.argmax(CAF_DC)]
CAF = getCAF(inputIQ, FFTsize, nSubC_Est, CPLen)

symLenEst = symLenList[np.argmax(CAF_DC)][np.argmax(CAF[freqBinList[np.argmax(CAF_DC)]])]
print(nSubC_Est, symLenEst)

256 272


In [28]:
f = open("./inputJson/test.json")
loadedJson = json.load(f)
print(loadedJson["data_path"])

/project/iarpa/dataset/cyclo_modul_OFDM/simulation/test/


In [2]:
import os
directory = '/project/iarpa/dataset/cyclo_modul_OFDM/simulation/walk_test'
os.walk(directory)

# [x[0] for x in os.walk(directory)]
for x in os.walk(directory):
    

SyntaxError: incomplete input (3158903244.py, line 7)

In [3]:
    CPLenList = np.array([np.array(['Extended', 'Normal']),\
        np.array(['Extended', 'Medium', 'Normal']),\
        np.array(['Extended', 'Normal']),\
        np.array(['Normal']), np.array(['Normal'])], dtype=object)

In [5]:
a = np.load('./result/nUser_1_wlanHE_Normal_1024qam.npy', allow_pickle=True)
a

array([[array([[400., 400.],
               [400., 400.],
               [400., 400.],
               [400., 400.],
               [400., 400.],
               [400., 400.],
               [400., 400.],
               [400., 400.],
               [400., 400.],
               [400., 400.],
               [400., 400.]]), array([[100.,  75.,  50.],
                                      [100.,  75.,  50.],
                                      [100.,  75.,  50.],
                                      [100.,  75.,  50.],
                                      [100.,  75.,  50.],
                                      [100.,  75.,  50.],
                                      [100.,  75.,  50.],
                                      [100.,  75.,  50.],
                                      [100.,  75.,  50.],
                                      [100.,  75.,  50.],
                                      [100.,  75.,  50.]]),
        array([[100., 100.],
               [100., 100.],
            

In [1]:
import numpy as np
import json
from utilities import *
import torch
# print(torch.version.cuda)

In [1]:
load_out = np.fromfile('/project/iarpa/dataset/cyclo_modul_OFDM/walk_test/CFOCorr/wlanHT_Extended_64_0_100_20_0.4_2.32cf',\
    dtype=np.float32)
print(load_out.shape)
data = load_out[np.arange(0, load_out.shape[0], 2)] +\
                    1j * load_out[np.arange(1, load_out.shape[0], 2)]
print(data.shape)
findFirstIndex(data[1600:], 64, 16)

NameError: name 'np' is not defined

In [6]:
a = np.array([1, 3, 2])
a[:-1]

array([1, 3])